server:
  port: 80 # 应用服务 WEB 访问端口
spring:
  application:
    name: reggie # 应用名称
  shardingsphere:
    enabled: true
    datasource:
      names: master,slave0
      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动
        url: jdbc:mysql://192.168.0.9:3306/reggie?useUnicode=true&CharacterEncoding=UTF-8&serverTimezone=UTC # 数据库连接地址
        username: admin # 数据库密码
        password: admin # 数据库密码
      # 从数据源
      slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动
        url: jdbc:mysql://192.168.0.3:3306/reggie?useUnicode=true&CharacterEncoding=UTF-8&serverTimezone=UTC # 数据库连接地址
        username: root # 数据库密码
        password: root # 数据库密码
    masterslave:
      # 负载均衡:轮循
      load-balance-algorithm-type: round_robin
      # 最终的数据源名称
      name: dataSource
      # 主数据源是谁
      master-data-source-name: master
      # 从数据源是那些
      slave-data-source-names:
        - slave0
    props:
      sql:
        show: true # 显示日志
  main:
    # 允许Bean覆盖
    allow-bean-definition-overriding: true

  redis:
    host: localhost
    port: 6379
    database: 0
  cache:
    redis:
      time-to-live: 1800000 # 缓存数据的过期时间

  # 配置邮箱发送者(企业等)
  mail:
    host: smtp.qq.com
    username: reggieuser@qq.com # 发送者的邮箱地址，例如：123@qq.com
    password: fiiwggdiqnwabejc # 邮箱授权值
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: auto
          starttls:
            enable: true
            required: true




mybatis-plus:
  mapper-locations: classpath:mapper/*.xml #指定Mybatis的Mapper文件
  type-aliases-package: com.study.reggie.entities #指定Mybatis的实体目录
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id # 主键生成策略:雪花算法


reggie:
  img-path: E:\66370\Pictures\reggie\ # 图片转存位置，绝对路径